<?php /* Smarty version 2.6.18-dev, created on 2014-07-29 12:24:49
         compiled from wiki:SlideShare */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'wiki:SlideShare', 1, false),array('modifier', 'escape', 'wiki:SlideShare', 1, false),array('modifier', 'validate', 'wiki:SlideShare', 1, false),)), $this); ?>
<object width="<?php echo ((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['width'])) ? $this->_run_mod_handler('default', true, $_tmp, 425) : smarty_modifier_default($_tmp, 425)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
" height="<?php echo ((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['height'])) ? $this->_run_mod_handler('default', true, $_tmp, 355) : smarty_modifier_default($_tmp, 355)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
"><param name="movie" value="http://static.slidesharecdn.com/swf/ssplayer<?php echo ((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['player'])) ? $this->_run_mod_handler('default', true, $_tmp, 2) : smarty_modifier_default($_tmp, 2)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
.swf?doc=<?php echo ((is_array($_tmp=$this->_tpl_vars['doc'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
<?php if (isset ( $this->_tpl_vars['norelated'] )): ?>&rel=0<?php endif; ?><?php if (isset ( $this->_tpl_vars['start'] )): ?>&startSlide=<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['start'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')))) ? $this->_run_mod_handler('validate', true, $_tmp, 'int') : smarty_modifier_validate($_tmp, 'int')); ?>
<?php endif; ?>" /><param name="allowFullScreen" value="true"/><param name="allowScriptAccess" value="always"/><embed  src="http://static.slidesharecdn.com/swf/ssplayer<?php echo ((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['player'])) ? $this->_run_mod_handler('default', true, $_tmp, 2) : smarty_modifier_default($_tmp, 2)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
.swf?doc=<?php echo ((is_array($_tmp=$this->_tpl_vars['doc'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="<?php echo ((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['width'])) ? $this->_run_mod_handler('default', true, $_tmp, 425) : smarty_modifier_default($_tmp, 425)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
" height="<?php echo ((is_array($_tmp=((is_array($_tmp=@$this->_tpl_vars['height'])) ? $this->_run_mod_handler('default', true, $_tmp, 355) : smarty_modifier_default($_tmp, 355)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); ?>
"></embed></object>